# Generated by Django 5.2.7 on 2025-10-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='img',
            field=models.FileField(default='salom.jpg', upload_to='media/news'),
        ),
    ]
